---
- name: "Creates backend app directory"
  file:
    path: ~/backend
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: artifact.tar.gz
    dest: "~/backend/artifact.tar.gz"

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend
    tar -zxvf artifact.tar.gz
    rm -rf artifact.tar.gz
- name: "Install dependencies for project"
  shell: |
    cd ~/backend
    npm install
- name: "Executing node"
  shell: |
    export
    cd ~/backend
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu