---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: ~/project/artifact.tar.gz
    dest: "~/backend-app/artifact.tar.gz"

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend-app
    tar -zxvf artifact.tar.gz
    rm -rf artifact.tar.gz
- name: "Install dependencies for project"
  shell: |
    cd ~/backend-app
    npm install
    pm2 stop default
    pm2 start npm -- start

- name:  start app
  command:  pm2 start main.js
  args:
    chdir: ~/backend-app/dist
  environment:
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
# - name: print message
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"

# - name: "Configure pm2 to start as service"
#   shell: |
#     env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu